version: "3"
services:

  db:
    image: mysql:8.0
    container_name: accountability_db
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - accountability

  redis:
    image: redis:6.2-alpine
    container_name: accountability_redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    entrypoint: >
      redis-server
        --loglevel warning 
        --appendonly yes
        --requirepass redispass
    networks:
      - accountability
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  app:
      container_name: data_ingester
      build: ./
      command: python3 -m app run --host=0.0.0.0 --port=5000
      ports:
          - "5001:5000"
      depends_on:
      - redis
      - db
      environment:
          PYTHONUNBUFFERED: 1
          DEBUG: "0"
          REDIS_HOST: redis
          REDIS_PORT: 6379
          REDIS_USER: guest
          REDIS_PASSWORD: redispass
          DB_HOST: db
          DB_USER: root
          DB_PASSWORD: root
          DB_PORT: 3306
          DB_NAME: accountability_db
      networks:
        - accountability

  worker:
    build: ./
    command: celery -A ingester_app.data_ingester_async.celery worker -l info --without-mingle --without-gossip
    volumes:
      - .:/usr/src/app
    environment:
      FLASK_DEBUG: 1
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USER: guest
      REDIS_PASSWORD: redispass
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_PORT: 3306
      DB_NAME: accountability_db
    depends_on:
      - app
      - redis
      - db
    networks:
      - accountability

  celery-beat:
    build: ./
    command: celery -A ingester_app.data_ingester_async.celery beat -l info
    volumes:
      - ./project/:/usr/src/app/
    environment:
      FLASK_DEBUG: 1
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USER: guest
      REDIS_PASSWORD: redispass
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_PORT: 3306
      DB_NAME: accountability_db
    depends_on:
      - app
      - redis
      - worker
    networks:
      - accountability

#  dashboard:
#    build: ./
#    command: celery --app ingester_app.data_ingester_async.celery flower --port=5555
#    ports:
#      - "5556:5555"
#    environment:
#      FLASK_DEBUG: 1
#      REDIS_HOST: redis
#      REDIS_PORT: 6379
#      REDIS_USER: guest
#      REDIS_PASSWORD: redispass
#    depends_on:
#      - app
#      - redis
#      - worker
#    networks:
#      - accountability

networks:
  accountability:
    driver: bridge

volumes:
  db:
    driver: local
