version: "3"
services:
    cache:
        container_name: accountability_cache
        image: redis:6.2-alpine
        restart: always
        ports:
          - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass redispass
        volumes:
          - cache:/data
        networks:
          - accountability
    app:
        container_name: data_ingester
        build: ./
        ports:
            - "5001:5000"
        depends_on:
        - cache
        environment:
            PYTHONUNBUFFERED: 1
            REDIS_HOST: cache
            REDIS_PORT: 6379
            REDIS_PASSWORD: redispass
        networks:
          - accountability

volumes:
  cache:
    driver: local

networks:
  accountability:
    driver: bridge